### ISSUE TITLE
MijnAfvalWijzer plugin

### ISSUE THREAD

**Issue by hitzel** [wez3/domoboard-plugins#33]
Is there a possibility to make a plugin for MijnAfvalWijzer. MijnAfvalWijzer is a website with an overview for collection trash. It is possible to filter it by filling in your postal code an number and number add-on

Website adres
http://www.mijnafvalwijzer.nl

**Comment by squandor** [comment]
Hi Hitzel,

I think thats possible. The only problem for me is if i fill in my zipcode my adres came up but there is no information in the site.. Do you have an zipcode which does work so i can test with it?

**Comment by hitzel** [comment]
postalcode is 7463 ED number 3. I'd like to see a view of the month

**Comment by squandor** [comment]
Hi Hitzel, the plugin works with some bugs for some people. you can try and install the plugin using the settings page.
